---
- name: set ip
  hosts: R
  gather_facts: no
  tasks:
    - name: enable interfaces
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            enabled: yes
      with_items:
        - { name: Ethernet0/1 }
        - { name: Ethernet0/2 }
    
    - name: set ip addresses
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip }}"
        state: merged
      with_items:
        - { name: Ethernet0/1 ,ip: 192.168.1.1/24, host: R1 }
        - { name: Ethernet0/2 ,ip: 192.168.12.1/24, host: R1 }
        - { name: Ethernet0/1 ,ip: 192.168.2.1/24, host: R2 }
        - { name: Ethernet0/2 ,ip: 192.168.12.2/24, host: R2 }
      when: inventory_hostname == item.host

    - name: configure static routes
      cisco.ios.ios_config:
        lines:
          - ip route {{ item.prefix }} {{ item.next_hop }}
      with_items:
        - { prefix: 192.168.2.0 255.255.255.0, next_hop: 192.168.12.2, host: R1 }
        - { prefix: 192.168.1.0 255.255.255.0, next_hop: 192.168.12.1, host: R2 }
      when: inventory_hostname == item.host

    - name: show ip route
      ios_command:
        commands:
          - show ip route
      register: show_route

    - debug:
        var: show_route.stdout_lines
