---
- name: set ip
  hosts: R
  gather_facts: no
  tasks:
    - name: enable int
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            enabled: yes
      with_items:
        - { name: Ethernet0/1 }
        - { name: Ethernet0/2 }
    - name: set ip
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip }}"
        state: merged
      with_items:
        - { name: Ethernet0/1 ,ip: 192.168.1.1/24, host: R1 }
        - { name: Ethernet0/2 ,ip: 192.168.12.1/24, host: R1 }
        - { name: Ethernet0/1 ,ip: 192.168.2.1/24, host: R2 }
        - { name: Ethernet0/2 ,ip: 192.168.12.2/24, host: R2 }
      when: inventory_hostname == item.host
